import { Familia, Instituicao, Item } from './types';

export const MOCK_FAMILIAS: Familia[] = [
  {
    id: 1,
    nomeResponsavel: 'Elizete da Silva',
    cpf: '12345678901',
    telefone: '54991234567',
    telefoneSecundario: '5432201122',
    dataHoraCadastro: '2026-06-20T08:38:09',
    dataHoraAtualizacao: '2026-06-22T10:08:41',
    qtdIntegrantes: 4,
    rendaFamiliarTotal: 1412.0,
    qtdCriancas: 2,
    qtdAdolescentes: 0,
    qtdIdosos: 0,
    possuiGestante: true,
    possuiLactante: false,
    situacaoCadastro: 'ATIVO',
    statusEmpregoResponsavel: 'TRABALHO_AUTONOMO_INFORMAL',
    possuiCadastroUnico: true,
    numeroNis: '12345678910',
    tipoMoradia: 'ALUGADA',
    possuiMembroPcd: false,
    historicoDoencasCronicas: 'Responsável relata quadro de asma crônica na criança mais nova.',
    possuiDependenciaQuimica: false,
    parecerDoAssistenteSocial: 'Família reside em imóvel alugado com infiltrações. Necessita de inclusão urgente no programa de distribuição de cestas básicas e acompanhamento da gestação.',
    observacoes: '',
    endereco: { id: 1, cep: '95034000', bairro: 'Centro', rua: 'Rua Flores', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '100', complemento: 'Próximo à paróquia central' },
  },
  {
    id: 2,
    nomeResponsavel: 'João Carlos Pereira',
    cpf: '98765432100',
    telefone: '54987654321',
    telefoneSecundario: '',
    dataHoraCadastro: '2026-05-15T14:20:00',
    dataHoraAtualizacao: '2026-06-01T09:00:00',
    qtdIntegrantes: 3,
    rendaFamiliarTotal: 900.0,
    qtdCriancas: 1,
    qtdAdolescentes: 1,
    qtdIdosos: 0,
    possuiGestante: false,
    possuiLactante: false,
    situacaoCadastro: 'ATIVO',
    statusEmpregoResponsavel: 'DESEMPREGADO',
    possuiCadastroUnico: true,
    numeroNis: '98765432100',
    tipoMoradia: 'CEDIDA_FAVOR',
    possuiMembroPcd: false,
    historicoDoencasCronicas: '',
    possuiDependenciaQuimica: false,
    parecerDoAssistenteSocial: 'Família em situação de vulnerabilidade. Responsável desempregado há 6 meses.',
    observacoes: 'Adolescente em idade escolar.',
    endereco: { id: 2, cep: '95010010', bairro: 'São Pelegrino', rua: 'Av. Júlio de Castilhos', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '450', complemento: 'Apto 12' },
  },
  {
    id: 3,
    nomeResponsavel: 'Maria Aparecida Santos',
    cpf: '11122233344',
    telefone: '54992223344',
    telefoneSecundario: '5432119900',
    dataHoraCadastro: '2026-04-10T11:00:00',
    dataHoraAtualizacao: '2026-04-10T11:00:00',
    qtdIntegrantes: 6,
    rendaFamiliarTotal: 2100.0,
    qtdCriancas: 3,
    qtdAdolescentes: 1,
    qtdIdosos: 1,
    possuiGestante: false,
    possuiLactante: true,
    situacaoCadastro: 'PENDENTE_ATUALIZACAO',
    statusEmpregoResponsavel: 'EMPREGO_FORMAL',
    possuiCadastroUnico: false,
    numeroNis: '',
    tipoMoradia: 'PROPRIA',
    possuiMembroPcd: true,
    historicoDoencasCronicas: 'Idoso com diabetes tipo 2 e hipertensão.',
    possuiDependenciaQuimica: false,
    parecerDoAssistenteSocial: 'Atualização cadastral necessária. Renda declarada não corresponde com situação domiciliar.',
    observacoes: '',
    endereco: { id: 3, cep: '95020050', bairro: 'Madureira', rua: 'Rua Ernesto Alves', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '78', complemento: '' },
  },
  {
    id: 4,
    nomeResponsavel: 'Carlos Eduardo Oliveira',
    cpf: '55566677788',
    telefone: '54993334455',
    telefoneSecundario: '',
    dataHoraCadastro: '2026-03-02T09:30:00',
    dataHoraAtualizacao: '2026-05-20T16:00:00',
    qtdIntegrantes: 2,
    rendaFamiliarTotal: 0.0,
    qtdCriancas: 0,
    qtdAdolescentes: 0,
    qtdIdosos: 0,
    possuiGestante: false,
    possuiLactante: false,
    situacaoCadastro: 'INATIVO',
    statusEmpregoResponsavel: 'APOSENTADO_PENSIONISTA',
    possuiCadastroUnico: true,
    numeroNis: '55566677788',
    tipoMoradia: 'ALUGADA',
    possuiMembroPcd: false,
    historicoDoencasCronicas: '',
    possuiDependenciaQuimica: false,
    parecerDoAssistenteSocial: 'Família saiu da área de atendimento.',
    observacoes: 'Mudou para outro município.',
    endereco: { id: 4, cep: '95040100', bairro: 'Lourdes', rua: 'Rua Garibaldi', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '233', complemento: '' },
  },
  {
    id: 5,
    nomeResponsavel: 'Ana Paula Rodrigues',
    cpf: '33344455566',
    telefone: '54994445566',
    telefoneSecundario: '',
    dataHoraCadastro: '2026-06-01T15:00:00',
    dataHoraAtualizacao: '2026-06-01T15:00:00',
    qtdIntegrantes: 5,
    rendaFamiliarTotal: 1800.0,
    qtdCriancas: 2,
    qtdAdolescentes: 2,
    qtdIdosos: 0,
    possuiGestante: false,
    possuiLactante: false,
    situacaoCadastro: 'ATIVO',
    statusEmpregoResponsavel: 'TRABALHO_AUTONOMO_INFORMAL',
    possuiCadastroUnico: true,
    numeroNis: '33344455566',
    tipoMoradia: 'PROPRIA',
    possuiMembroPcd: false,
    historicoDoencasCronicas: '',
    possuiDependenciaQuimica: false,
    parecerDoAssistenteSocial: '',
    observacoes: '',
    endereco: { id: 5, cep: '95050200', bairro: 'Santa Catarina', rua: 'Rua XV de Novembro', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '512', complemento: 'Casa fundos' },
  },
];

export const MOCK_INSTITUICOES: Instituicao[] = [
  {
    id: 1,
    nome: 'Conexão Solidária Central',
    cnpj: '12345678000100',
    nomeResponsavel: 'Diego Pereira',
    telefoneResponsavel: '5498769045',
    emailResponsavel: 'diego.pereira@conexaosolidaria.org',
    tipo: 'CENTRAL',
    telefoneInstituicao: '5433727632',
    emailInstituicao: 'contato@conexaosolidaria.org',
    situacaoCadastro: 'ATIVO',
    endereco: { id: 1, cep: '95010000', bairro: 'Centro', rua: 'Rua Sinimbu', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '1580', complemento: 'Sala 201' },
  },
  {
    id: 2,
    nome: 'Filial Norte',
    cnpj: '12345678000281',
    nomeResponsavel: 'Carla Mendes',
    telefoneResponsavel: '54991110022',
    emailResponsavel: 'carla.mendes@conexaosolidaria.org',
    tipo: 'FILIAL',
    telefoneInstituicao: '5433001122',
    emailInstituicao: 'norte@conexaosolidaria.org',
    centralId: 1,
    situacaoCadastro: 'ATIVO',
    endereco: { id: 2, cep: '95045100', bairro: 'Nossa Senhora de Lourdes', rua: 'Rua Gustavo Kuhn', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '320', complemento: '' },
  },
  {
    id: 3,
    nome: 'Filial Sul',
    cnpj: '12345678000362',
    nomeResponsavel: 'Rafael Costa',
    telefoneResponsavel: '54992223344',
    emailResponsavel: 'rafael.costa@conexaosolidaria.org',
    tipo: 'FILIAL',
    telefoneInstituicao: '5433445566',
    emailInstituicao: 'sul@conexaosolidaria.org',
    centralId: 1,
    situacaoCadastro: 'ATIVO',
    endereco: { id: 3, cep: '95060300', bairro: 'Madureira', rua: 'Rua Qualquer', cidade: 'Caxias do Sul', estadoUF: 'RS', numero: '100', complemento: 'Ponto de ônibus em frente' },
  },
];

export const MOCK_ITENS: Item[] = [
  { id: 1, nome: 'Arroz Branco Tio Juca Tipo 1 (1kg)', descricao: 'Pacote de arroz polido', codigoBarras: '7891234567890', categoria: 'ALIMENTO', unidadeMedida: 'KG', dataCadastro: '2026-06-20', ativo: true, exigeControleValidade: true, estoque: 45 },
  { id: 2, nome: 'Feijão Preto (1kg)', descricao: 'Pacote de feijão preto', codigoBarras: '7891234567891', categoria: 'ALIMENTO', unidadeMedida: 'KG', dataCadastro: '2026-06-20', ativo: true, exigeControleValidade: true, estoque: 32 },
  { id: 3, nome: 'Óleo de Soja (900ml)', descricao: 'Garrafa de óleo de soja', codigoBarras: '7891234567892', categoria: 'ALIMENTO', unidadeMedida: 'LITRO', dataCadastro: '2026-06-20', ativo: true, exigeControleValidade: true, estoque: 28 },
  { id: 4, nome: 'Macarrão Espaguete (500g)', descricao: 'Pacote de macarrão', codigoBarras: '7891234567893', categoria: 'ALIMENTO', unidadeMedida: 'PACOTE', dataCadastro: '2026-06-20', ativo: true, exigeControleValidade: true, estoque: 60 },
  { id: 5, nome: 'Shampoo Anticaspa (200ml)', descricao: 'Shampoo para uso diário', codigoBarras: '7891234567894', categoria: 'HIGIENE_PESSOAL', unidadeMedida: 'UNIDADE', dataCadastro: '2026-06-21', ativo: true, exigeControleValidade: false, estoque: 18 },
  { id: 6, nome: 'Sabonete (90g)', descricao: 'Sabonete barra', codigoBarras: '7891234567895', categoria: 'HIGIENE_PESSOAL', unidadeMedida: 'UNIDADE', dataCadastro: '2026-06-21', ativo: true, exigeControleValidade: false, estoque: 50 },
  { id: 7, nome: 'Detergente Ypê (500ml)', descricao: 'Detergente neutro', codigoBarras: '7891234567896', categoria: 'LIMPEZA', unidadeMedida: 'UNIDADE', dataCadastro: '2026-06-21', ativo: true, exigeControleValidade: false, estoque: 22 },
  { id: 8, nome: 'Fralda Descartável M (pacote 20un)', descricao: 'Fraldas tamanho M', codigoBarras: '7891234567897', categoria: 'HIGIENE_PESSOAL', unidadeMedida: 'PACOTE', dataCadastro: '2026-06-22', ativo: true, exigeControleValidade: false, estoque: 10 },
];
